services:
  ckan:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      TZ: UTC
      CKAN_SQLALCHEMY_URL: postgresql://ckan_default:pass@postgres/ckan_test
      CKAN_DATASTORE_WRITE_URL: postgresql://datastore_write:pass@postgres/datastore_test
      CKAN_DATASTORE_READ_URL: postgresql://datastore_read:pass@postgres/datastore_test
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    depends_on:
      - postgres
      - solr
      - redis
    volumes:
      - ./ckanext:/srv/app/src/ckanext-schemingdcat/ckanext

  solr:
    image: ckan/ckan-solr:2.9-solr9-spatial
    logging:
      driver: none
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:8983/solr/"]

  postgres:
    image: ckan/ckan-postgres-dev:2.9
    logging:
      driver: none
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ckan_default", "-d", "ckan_test"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    logging:
      driver: none
    healthcheck:
      test: ["CMD", "redis-cli", "-e", "QUIT"]